### ISSUE TITLE
Error fetching package

### ISSUE THREAD

**Issue by jamie-tillman** [picco/drupalstack#15]
Running `my-project/bin/start-services.sh` on Win10 using Git bash shell resulted in the following after a very long series of apt-get actions.  Re-running produces the same.  Any ideas?
```
Err http://deb.debian.org jessie-backports/main amd64 Packages

Err http://deb.debian.org jessie-backports/main amd64 Packages
  404  Not Found
Fetched 19.8 MB in 9s (2095 kB/s)
W: Failed to fetch http://deb.debian.org/debian/dists/jessie-backports/main/binary-amd64/Packages  404  Not Found

E: Some index files failed to download. They have been ignored, or old ones used instead.
Service 'httpd' failed to build: The command '/bin/sh -c apt-get update   && apt-get install -y      nano      openssl   && rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100
```

**Comment by raudam** [comment]
Can't test to confirm but I think the solution was to update the base packages used [for apache](https://github.com/adminteractive/drupalstack/blob/master/services/httpd/Dockerfile#L1) to at least httpd:2.4.39 and [php](https://github.com/adminteractive/drupalstack/blob/master/services/php/Dockerfile#L1) to php:7.0.33-fpm.

If that doesn't work then you can try adding 
`RUN printf "deb http://archive.debian.org/debian/ jessie main\ndeb-src http://archive.debian.org/debian/ jessie main\ndeb http://security.debian.org jessie/updates main\ndeb-src http://security.debian.org jessie/updates main" > /etc/apt/sources.list`
To [php](https://github.com/adminteractive/drupalstack/blob/master/services/php/Dockerfile), [mysql](https://github.com/adminteractive/drupalstack/blob/master/services/mysql/Dockerfile) and [apache](https://github.com/adminteractive/drupalstack/blob/master/services/httpd/Dockerfile) right after the first line.

That said, development for this has stopped for a while now and is unlikely to start back so I urge  you to migrate to [ddev](https://ddev.readthedocs.io/en/stable/) or [lando](https://docs.lando.dev/).

**Comment by jamie-tillman** [comment]
Thanks for the much-needed tip!  Trying to find a good Drupal 8 contribution starter environment that leverages Docker (as I'm stuck in Microsoft-land) and the landscape is littered with half-baked tutorials and abandoned projects!
